ssh_authorized_keys:
- ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCd+S4tYjOgjkzFaj97z49Ktojnq85vkBJe4vvA1V/2XyTcl81CTjalQiEPVJJMkG2DY6xEbAC1I+kjBgt7MnmjViOsTXZ8o3a1/0iOIW7C7VUaKtiJW0SEro9ezTSrDoyUE3+raIgFIYrII0Vh4a0FP3Xntn1zNTUzEnDmbwZ+taggupME25LTbMXf4pnCkUCUPE7gmRr7HTUYy6ZKhm+6IWpHw9yrrkmFkJud+9xD0uqv0Gc9P5jCjIFM6SUxIBqDfphfmVXM3QEI6QwupvqAlXHRPLFhHHJOQVh7nUHTzcSua4H5ZwWU1ps7VrAx3aABJhwa4w1CzatDrxVlIuFgV//y1gzgUGSyxHtW+l21Qy0+zJBUlfiB1iXEMS4rLbTJaJDanon9NxfVYAuyQv7DvhRy0BDeYKaQ8MSId4g//uq8nsYNGuNmPxSw0tvUox/RWeYeOYM0d+jaUzv4NuCu74I+EUr/JvFbnmoWoW0dQJr9cFfn4e8DXfc+wf5vs5M= piron@PAR-ML-00026277
hostname: k3os.demo.local
k3os:
  password: $1$HNFtNw/J$s44lXqWPGx47G/.pauptG/                                                                        
  dns_nameservers: 
  - 192.168.1.249
  ntp_servers:
  - 0.fr.pool.ntp.org
  - 1.fr.pool.ntp.org
  k3s_args:
  - server
